sudo: false

language: php

php:
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

services:
    - mysql

before_install:
    - export SYMFONY_ENV=prod
    - mysql -e 'create database symfony;' -u root

install:
    - composer install --no-dev --optimize-autoloader

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

before_script:

    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
    - php bin/console doctrine:fixtures:load

script:
    - phpunit tests