<?php

namespace AppBundle\Repository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPrice($name){
        $qb = $this->createQueryBuilder('p')
            ->select('p.value')
            ->where('p.name = :name')
            ->setParameter(':name', $name)
        ;
        
        $result = $qb
            ->getQuery()
            ->getSingleResult();
            
        ;

        return $result['value'];
    }
}
