payment:
    resource: "@PaymentBundle/Controller/"
    type:     annotation


app:
    resource: "@AppBundle/Controller/"
    type:     annotation

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"