ticket_system:
    resource: "@TicketSystemBundle/Controller/"
    type:     annotation
    prefix:   /

payment:
    resource: "@PaymentBundle/Controller/"
    type:     annotation


app:
    resource: "@AppBundle/Controller/"
    type:     annotation

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"


payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"


payum_payout:
    resource: "@PayumBundle/Resources/config/routing/payout.xml"


payum_sync:
    resource: "@PayumBundle/Resources/config/routing/sync.xml"


payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"


payum_refund:
    resource: "@PayumBundle/Resources/config/routing/refund.xml"

