# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.louvrepricing:
        class:        AppBundle\Pricing\LouvrePricing
        arguments:    ["@doctrine.orm.default_entity_manager", "@Session"]


    app.datechecking:
        class:        AppBundle\DateChecking\DateChecking
